# Bias Anonymizer Configuration File
# This file configures the behavior of the bias anonymizer

# Detection settings
detect_bias: true
detect_pii: true

# Anonymization strategy: redact, replace, or custom
# IMPORTANT: Use 'custom' to respect individual operator configurations
anonymization_strategy: custom

# Confidence threshold for detection (0.0 to 1.0)
# Lower values mean more aggressive detection
confidence_threshold: 0.5

# Language for analysis
language: en

# Fields that should NEVER be anonymized (preserve for matching)
preserve_fields:
  # Core business fields - needed for matching
  - core.rank.code
  - core.rank.id
  - core.employeeType.code
  - core.jobCode
  - core.gcrs.businessDivisionCode
  - core.gcrs.businessUnitCode
  - core.gcrs.businessAreaCode
  - core.gcrs.businessSectorCode
  - core.gcrs.businessSegmentCode
  - core.gcrs.businessFunctionCode
  
  # Work location codes (not descriptions)
  - core.workLocation.code
  - core.workLocation.buildingCode
  - core.workLocation.postalCode
  - core.workLocation.stateCode
  - core.workLocation.countryCode
  
  # Experience metadata
  - experience.crossDivisionalExperience
  - experience.internationalExperience
  - experience.timeInCurrentRoleInDays
  
  # Education and certifications (skills-based)
  - qualification.educations[*].degree
  - qualification.educations[*].areaOfStudy
  - qualification.educations[*].completionYear
  - qualification.certifications
  
  # System fields
  - version
  - completionScore
  - userId
  - externalSourceType

# Fields that should ALWAYS be anonymized (contain PII/bias)
always_anonymize_fields:
  # Descriptions that might contain bias
  - core.rank.description
  - core.employeeType.description
  - core.businessTitle
  - core.gcrs.businessDivisionDescription
  - core.gcrs.businessUnitDescription
  - core.gcrs.businessAreaDescription
  - core.gcrs.businessSectorDescription
  - core.gcrs.businessSegmentDescription
  - core.gcrs.businessFunctionDescription
  
  # Location descriptions (might reveal demographic info)
  - core.workLocation.description
  - core.workLocation.city
  - core.workLocation.state
  - core.workLocation.county
  - core.workLocation.country
  - core.workLocation.region
  
  # Dates that could reveal age
  - core.enterpriseSeniorityDate
  
  # Work eligibility (nationality/immigration status)
  - workEligibility
  
  # Language proficiency (potential bias)
  - language.languages
  
  # Affiliations (could reveal personal info)
  - affiliation.awards
  - affiliation.boards
  - affiliation.mandates
  - affiliation.memberships
  
  # Experience descriptions
  - experience.experiences[*].company
  - experience.experiences[*].description
  - experience.experiences[*].jobTitle
  - experience.experiences[*].country.description
  
  # Education institution names (could reveal background)
  - qualification.educations[*].institutionName
  - qualification.educations[*].achievements
  
  # Career preferences (might contain bias)
  - careerAspirationPreference
  - careerLocationPreference
  - careerRolePreference
  
  # Audit fields (might contain names)
  - language.createdBy
  - language.lastModifiedBy
  - affiliation.createdBy
  - affiliation.lastModifiedBy
  - experience.createdBy
  - experience.lastModifiedBy
  - qualification.createdBy
  - qualification.lastModifiedBy

# Fields that need special handling
special_handling_fields:
  # Hash user ID instead of removing
  userId: hash
  
  # Generalize dates to year only
  experience.experiences[*].startDate: year_only
  experience.experiences[*].endDate: year_only
  createdDateTime: remove
  lastModifiedDateTime: remove
  
  # Categorize reporting distance
  core.reportingDistance.geb: categorize
  core.reportingDistance.ceo: categorize
  core.reportingDistance.chairman: categorize

# Anonymization operators per entity type
# Available operators: replace, mask, hash, encrypt, redact, keep
operators:
  # PII entities
  PERSON: replace
  EMAIL_ADDRESS: mask
  PHONE_NUMBER: hash
  LOCATION: replace
  DATE_TIME: replace
  CREDIT_CARD: mask
  IP_ADDRESS: mask
  US_SSN: mask
  
  # Bias indicators - redact by default (removes text)
  GENDER_BIAS: redact
  RACE_BIAS: redact
  AGE_BIAS: redact
  DISABILITY_BIAS: redact
  MARITAL_STATUS_BIAS: redact
  FAMILY_STATUS_BIAS: redact  # Alias for marital status
  NATIONALITY_BIAS: redact
  SEXUAL_ORIENTATION_BIAS: redact
  RELIGION_BIAS: redact
  POLITICAL_AFFILIATION_BIAS: redact
  POLITICAL_BIAS: redact  # Alias
  SOCIOECONOMIC_BIAS: redact
  EDUCATION_BIAS: redact  # Part of socioeconomic
  MATERNITY_BIAS: redact
  PREGNANCY_BIAS: redact  # Alias
  UNION_BIAS: redact
  HEALTH_BIAS: redact
  CRIMINAL_BIAS: redact
  
  # Catch-all for bias indicators
  BIAS_INDICATOR: redact
  
  # Default operator for unspecified entities
  DEFAULT: replace

# Replacement values for replace operator
replacement_tokens:
  PERSON: "[NAME]"
  EMAIL_ADDRESS: "[EMAIL]"
  PHONE_NUMBER: "[PHONE]"
  LOCATION: "[LOCATION]"
  DATE_TIME: "[DATE]"
  CREDIT_CARD: "[CARD]"
  IP_ADDRESS: "[IP]"
  US_SSN: "[SSN]"
  GENDER_BIAS: "[GENDER]"
  RACE_BIAS: "[RACE]"
  AGE_BIAS: "[AGE]"
  DISABILITY_BIAS: "[DISABILITY]"
  MARITAL_STATUS_BIAS: "[MARITAL_STATUS]"
  NATIONALITY_BIAS: "[NATIONALITY]"
  SEXUAL_ORIENTATION_BIAS: "[ORIENTATION]"
  RELIGION_BIAS: "[RELIGION]"
  POLITICAL_AFFILIATION_BIAS: "[POLITICAL]"
  SOCIOECONOMIC_BIAS: "[BACKGROUND]"
  FAMILY_STATUS_BIAS: "[FAMILY]"
  EDUCATION_BIAS: "[EDUCATION]"
  DEFAULT: "[REDACTED]"

# Bias categories to detect (comment out for all)
bias_categories:
  - gender
  - race_ethnicity
  - age
  - disability
  - marital_status
  - nationality
  - sexual_orientation
  - religion
  - political_affiliation
  - socioeconomic_background
  - pregnancy_maternity
  - union_membership
  - health_condition
  - criminal_background

# Processing settings
preserve_structure: true
batch_size: 100
parallel_processing: false
